export default [
    {
        title:"Mã khách hàng",
        extract:"Mã khách hàng là mã giao dịch được quy định bởi nhà cung cấp dịch vụ. Mỗi khách hàng có một mã khác nhau giúp phân biệt được giữa các khách hàng với nhau.",
        groupType:"Database",
        tagSearch:["ma","khach","hang",'account','account_object','account_object_id'],
        detailId:"",
    },
    {
        title:"Mã khách hàng",
        extract:"Mã khách hàng là mã giao dịch được quy định bởi nhà cung cấp dịch vụ. Mỗi khách hàng có một mã khác nhau giúp phân biệt được giữa các khách hàng với nhau.",
        groupType:"Database",
        tagSearch:["ma","khach","hang",'account','account_object','account_object_id'],
        detailId:"",
    },
    {
        title:"Mã khách hàng",
        extract:"Mã khách hàng là mã giao dịch được quy định bởi nhà cung cấp dịch vụ. Mỗi khách hàng có một mã khác nhau giúp phân biệt được giữa các khách hàng với nhau.",
        groupType:"Database",
        tagSearch:["ma","khach","hang",'account','account_object','account_object_id'],
        detailId:"",
    },
    {
        title:"Mã khách hàng",
        extract:"Mã khách hàng là mã giao dịch được quy định bởi nhà cung cấp dịch vụ. Mỗi khách hàng có một mã khác nhau giúp phân biệt được giữa các khách hàng với nhau.",
        groupType:"Database",
        tagSearch:["ma","khach","hang",'account','account_object','account_object_id'],
        detailId:"",
    },
    {
        title:"Mã khách hàng",
        extract:"Mã khách hàng là mã giao dịch được quy định bởi nhà cung cấp dịch vụ. Mỗi khách hàng có một mã khác nhau giúp phân biệt được giữa các khách hàng với nhau.",
        groupType:"Database",
        tagSearch:["ma","khach","hang",'account','account_object','account_object_id'],
        detailId:"",
    },
    {
        title:"Mã khách hàng",
        extract:"Mã khách hàng là mã giao dịch được quy định bởi nhà cung cấp dịch vụ. Mỗi khách hàng có một mã khác nhau giúp phân biệt được giữa các khách hàng với nhau.",
        groupType:"Database",
        tagSearch:["ma","khach","hang",'account','account_object','account_object_id'],
        detailId:"",
    },
    {
        title:"Mã khách hàng",
        extract:"Mã khách hàng là mã giao dịch được quy định bởi nhà cung cấp dịch vụ. Mỗi khách hàng có một mã khác nhau giúp phân biệt được giữa các khách hàng với nhau.",
        groupType:"Database",
        tagSearch:["ma","khach","hang",'account','account_object','account_object_id'],
        detailId:"",
    },
    {
        title:"Mã khách hàng",
        extract:"Mã khách hàng là mã giao dịch được quy định bởi nhà cung cấp dịch vụ. Mỗi khách hàng có một mã khác nhau giúp phân biệt được giữa các khách hàng với nhau.",
        groupType:"Database",
        tagSearch:["ma","khach","hang",'account','account_object','account_object_id'],
        detailId:"",
    },
    {
        title:"Mã khách hàng",
        extract:"Mã khách hàng là mã giao dịch được quy định bởi nhà cung cấp dịch vụ. Mỗi khách hàng có một mã khác nhau giúp phân biệt được giữa các khách hàng với nhau.",
        groupType:"Database",
        tagSearch:["ma","khach","hang",'account','account_object','account_object_id'],
        detailId:"",
    },
    {
        title:"Mã khách hàng",
        extract:"Mã khách hàng là mã giao dịch được quy định bởi nhà cung cấp dịch vụ. Mỗi khách hàng có một mã khác nhau giúp phân biệt được giữa các khách hàng với nhau.",
        groupType:"Database",
        tagSearch:["ma","khach","hang",'account','account_object','account_object_id'],
        detailId:"",
    },
    {
            title:"Title",
            extract:"Nội dung miêu tả khái quát",
            groupType:"Database",
            tagSearch:["a","b"],
            detailId:"",
    },
    {
        title:"Title2",
        extract:"Nội dung miêu tả khái quát",
        groupType:"PBI",
        tagSearch:["z","x","test","b"],
        detailId:"",
    }
]